### PR TITLE
Correct version numbers in the documentation

### PR DESCRIPTION
**Pull request by Danconnolly**
Add comment about checking the correct versions.

Also correct path to rest README.MD

### CODE REVIEW

**Review by galt-tr — APPROVED** [review]
LGTM

**Comment by rt121212121** [comment]
Another version number that needs updating?

https://github.com/bitcoin-sv/block-headers-client/blob/0e27071ba729cfeb544cf0d84ba289dab0062596/app/src/main/java/io/bitcoinsv/headerSV/app/HeaderSVApplication.java#L27

**Comment by jadwahab** [comment]
don't have permission to push, will just create another PR for it

**Comment by jadwahab** [comment]
closing as it's covered with #21

**Pull request closed without merging**
